// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RoomAir.proto

package RoomAirManager;

/**
 * Protobuf type {@code RoomAirManager.hourlyAirTracker}
 */
public  final class hourlyAirTracker extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:RoomAirManager.hourlyAirTracker)
    hourlyAirTrackerOrBuilder {
private static final long serialVersionUID = 0L;
  // Use hourlyAirTracker.newBuilder() to construct.
  private hourlyAirTracker(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private hourlyAirTracker() {
    temperature_ = "";
    window_ = "";
    airPurifier_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private hourlyAirTracker(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            temperature_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            window_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            airPurifier_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return RoomAirManager.RoomAirImpl.internal_static_RoomAirManager_hourlyAirTracker_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return RoomAirManager.RoomAirImpl.internal_static_RoomAirManager_hourlyAirTracker_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            RoomAirManager.hourlyAirTracker.class, RoomAirManager.hourlyAirTracker.Builder.class);
  }

  public static final int TEMPERATURE_FIELD_NUMBER = 1;
  private volatile java.lang.Object temperature_;
  /**
   * <code>string temperature = 1;</code>
   */
  public java.lang.String getTemperature() {
    java.lang.Object ref = temperature_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      temperature_ = s;
      return s;
    }
  }
  /**
   * <code>string temperature = 1;</code>
   */
  public com.google.protobuf.ByteString
      getTemperatureBytes() {
    java.lang.Object ref = temperature_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      temperature_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int WINDOW_FIELD_NUMBER = 2;
  private volatile java.lang.Object window_;
  /**
   * <code>string window = 2;</code>
   */
  public java.lang.String getWindow() {
    java.lang.Object ref = window_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      window_ = s;
      return s;
    }
  }
  /**
   * <code>string window = 2;</code>
   */
  public com.google.protobuf.ByteString
      getWindowBytes() {
    java.lang.Object ref = window_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      window_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AIRPURIFIER_FIELD_NUMBER = 3;
  private volatile java.lang.Object airPurifier_;
  /**
   * <code>string airPurifier = 3;</code>
   */
  public java.lang.String getAirPurifier() {
    java.lang.Object ref = airPurifier_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      airPurifier_ = s;
      return s;
    }
  }
  /**
   * <code>string airPurifier = 3;</code>
   */
  public com.google.protobuf.ByteString
      getAirPurifierBytes() {
    java.lang.Object ref = airPurifier_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      airPurifier_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getTemperatureBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, temperature_);
    }
    if (!getWindowBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, window_);
    }
    if (!getAirPurifierBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, airPurifier_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getTemperatureBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, temperature_);
    }
    if (!getWindowBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, window_);
    }
    if (!getAirPurifierBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, airPurifier_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof RoomAirManager.hourlyAirTracker)) {
      return super.equals(obj);
    }
    RoomAirManager.hourlyAirTracker other = (RoomAirManager.hourlyAirTracker) obj;

    boolean result = true;
    result = result && getTemperature()
        .equals(other.getTemperature());
    result = result && getWindow()
        .equals(other.getWindow());
    result = result && getAirPurifier()
        .equals(other.getAirPurifier());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TEMPERATURE_FIELD_NUMBER;
    hash = (53 * hash) + getTemperature().hashCode();
    hash = (37 * hash) + WINDOW_FIELD_NUMBER;
    hash = (53 * hash) + getWindow().hashCode();
    hash = (37 * hash) + AIRPURIFIER_FIELD_NUMBER;
    hash = (53 * hash) + getAirPurifier().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static RoomAirManager.hourlyAirTracker parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static RoomAirManager.hourlyAirTracker parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static RoomAirManager.hourlyAirTracker parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static RoomAirManager.hourlyAirTracker parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static RoomAirManager.hourlyAirTracker parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static RoomAirManager.hourlyAirTracker parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static RoomAirManager.hourlyAirTracker parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static RoomAirManager.hourlyAirTracker parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static RoomAirManager.hourlyAirTracker parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static RoomAirManager.hourlyAirTracker parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static RoomAirManager.hourlyAirTracker parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static RoomAirManager.hourlyAirTracker parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(RoomAirManager.hourlyAirTracker prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code RoomAirManager.hourlyAirTracker}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:RoomAirManager.hourlyAirTracker)
      RoomAirManager.hourlyAirTrackerOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RoomAirManager.RoomAirImpl.internal_static_RoomAirManager_hourlyAirTracker_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RoomAirManager.RoomAirImpl.internal_static_RoomAirManager_hourlyAirTracker_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RoomAirManager.hourlyAirTracker.class, RoomAirManager.hourlyAirTracker.Builder.class);
    }

    // Construct using RoomAirManager.hourlyAirTracker.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      temperature_ = "";

      window_ = "";

      airPurifier_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return RoomAirManager.RoomAirImpl.internal_static_RoomAirManager_hourlyAirTracker_descriptor;
    }

    @java.lang.Override
    public RoomAirManager.hourlyAirTracker getDefaultInstanceForType() {
      return RoomAirManager.hourlyAirTracker.getDefaultInstance();
    }

    @java.lang.Override
    public RoomAirManager.hourlyAirTracker build() {
      RoomAirManager.hourlyAirTracker result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public RoomAirManager.hourlyAirTracker buildPartial() {
      RoomAirManager.hourlyAirTracker result = new RoomAirManager.hourlyAirTracker(this);
      result.temperature_ = temperature_;
      result.window_ = window_;
      result.airPurifier_ = airPurifier_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof RoomAirManager.hourlyAirTracker) {
        return mergeFrom((RoomAirManager.hourlyAirTracker)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(RoomAirManager.hourlyAirTracker other) {
      if (other == RoomAirManager.hourlyAirTracker.getDefaultInstance()) return this;
      if (!other.getTemperature().isEmpty()) {
        temperature_ = other.temperature_;
        onChanged();
      }
      if (!other.getWindow().isEmpty()) {
        window_ = other.window_;
        onChanged();
      }
      if (!other.getAirPurifier().isEmpty()) {
        airPurifier_ = other.airPurifier_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      RoomAirManager.hourlyAirTracker parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (RoomAirManager.hourlyAirTracker) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object temperature_ = "";
    /**
     * <code>string temperature = 1;</code>
     */
    public java.lang.String getTemperature() {
      java.lang.Object ref = temperature_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        temperature_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string temperature = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTemperatureBytes() {
      java.lang.Object ref = temperature_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        temperature_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string temperature = 1;</code>
     */
    public Builder setTemperature(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      temperature_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string temperature = 1;</code>
     */
    public Builder clearTemperature() {
      
      temperature_ = getDefaultInstance().getTemperature();
      onChanged();
      return this;
    }
    /**
     * <code>string temperature = 1;</code>
     */
    public Builder setTemperatureBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      temperature_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object window_ = "";
    /**
     * <code>string window = 2;</code>
     */
    public java.lang.String getWindow() {
      java.lang.Object ref = window_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        window_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string window = 2;</code>
     */
    public com.google.protobuf.ByteString
        getWindowBytes() {
      java.lang.Object ref = window_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        window_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string window = 2;</code>
     */
    public Builder setWindow(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      window_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string window = 2;</code>
     */
    public Builder clearWindow() {
      
      window_ = getDefaultInstance().getWindow();
      onChanged();
      return this;
    }
    /**
     * <code>string window = 2;</code>
     */
    public Builder setWindowBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      window_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object airPurifier_ = "";
    /**
     * <code>string airPurifier = 3;</code>
     */
    public java.lang.String getAirPurifier() {
      java.lang.Object ref = airPurifier_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        airPurifier_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string airPurifier = 3;</code>
     */
    public com.google.protobuf.ByteString
        getAirPurifierBytes() {
      java.lang.Object ref = airPurifier_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        airPurifier_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string airPurifier = 3;</code>
     */
    public Builder setAirPurifier(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      airPurifier_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string airPurifier = 3;</code>
     */
    public Builder clearAirPurifier() {
      
      airPurifier_ = getDefaultInstance().getAirPurifier();
      onChanged();
      return this;
    }
    /**
     * <code>string airPurifier = 3;</code>
     */
    public Builder setAirPurifierBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      airPurifier_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:RoomAirManager.hourlyAirTracker)
  }

  // @@protoc_insertion_point(class_scope:RoomAirManager.hourlyAirTracker)
  private static final RoomAirManager.hourlyAirTracker DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new RoomAirManager.hourlyAirTracker();
  }

  public static RoomAirManager.hourlyAirTracker getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<hourlyAirTracker>
      PARSER = new com.google.protobuf.AbstractParser<hourlyAirTracker>() {
    @java.lang.Override
    public hourlyAirTracker parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new hourlyAirTracker(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<hourlyAirTracker> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<hourlyAirTracker> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public RoomAirManager.hourlyAirTracker getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

