// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RoomAir.proto

package RoomAirManager;

public interface hourlyAirTrackerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RoomAirManager.hourlyAirTracker)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string temperature = 1;</code>
   */
  java.lang.String getTemperature();
  /**
   * <code>string temperature = 1;</code>
   */
  com.google.protobuf.ByteString
      getTemperatureBytes();

  /**
   * <code>string window = 2;</code>
   */
  java.lang.String getWindow();
  /**
   * <code>string window = 2;</code>
   */
  com.google.protobuf.ByteString
      getWindowBytes();

  /**
   * <code>string airPurifier = 3;</code>
   */
  java.lang.String getAirPurifier();
  /**
   * <code>string airPurifier = 3;</code>
   */
  com.google.protobuf.ByteString
      getAirPurifierBytes();
}
