// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RoomAir.proto

package RoomAirManager;

public final class RoomAirImpl {
  private RoomAirImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RoomAirManager_roomNum_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RoomAirManager_roomNum_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RoomAirManager_hourlyAirTracker_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RoomAirManager_hourlyAirTracker_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rRoomAir.proto\022\016RoomAirManager\"\027\n\007roomN" +
      "um\022\014\n\004room\030\001 \001(\005\"L\n\020hourlyAirTracker\022\023\n\013" +
      "temperature\030\001 \001(\t\022\016\n\006window\030\002 \001(\t\022\023\n\013air" +
      "Purifier\030\003 \001(\t2Y\n\007RoomAir\022N\n\017controllRoo" +
      "mAir\022\027.RoomAirManager.roomNum\032 .RoomAirM" +
      "anager.hourlyAirTracker0\001B\037\n\016RoomAirMana" +
      "gerB\013RoomAirImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_RoomAirManager_roomNum_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RoomAirManager_roomNum_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RoomAirManager_roomNum_descriptor,
        new java.lang.String[] { "Room", });
    internal_static_RoomAirManager_hourlyAirTracker_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_RoomAirManager_hourlyAirTracker_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RoomAirManager_hourlyAirTracker_descriptor,
        new java.lang.String[] { "Temperature", "Window", "AirPurifier", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
