// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RoomWaterDispenser.proto

package RoomWaterDispenser;

public interface expiredOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RoomWaterDispenser.expired)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string expiry = 1;</code>
   */
  java.lang.String getExpiry();
  /**
   * <code>string expiry = 1;</code>
   */
  com.google.protobuf.ByteString
      getExpiryBytes();
}
