// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RoomWaterDispenser.proto

package RoomWaterDispenser;

public interface lastReplacedOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RoomWaterDispenser.lastReplaced)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 room = 1;</code>
   */
  int getRoom();

  /**
   * <code>string lastReplacedDate = 2;</code>
   */
  java.lang.String getLastReplacedDate();
  /**
   * <code>string lastReplacedDate = 2;</code>
   */
  com.google.protobuf.ByteString
      getLastReplacedDateBytes();
}
