// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RoomWaterDispenser.proto

package RoomWaterDispenser;

public final class RoomWaterDispenserImpl {
  private RoomWaterDispenserImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RoomWaterDispenser_lastReplaced_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RoomWaterDispenser_lastReplaced_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RoomWaterDispenser_expired_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RoomWaterDispenser_expired_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030RoomWaterDispenser.proto\022\022RoomWaterDis" +
      "penser\"6\n\014lastReplaced\022\014\n\004room\030\001 \001(\005\022\030\n\020" +
      "lastReplacedDate\030\002 \001(\t\"\031\n\007expired\022\016\n\006exp" +
      "iry\030\001 \001(\t2c\n\022RoomWaterDispenser\022M\n\014filte" +
      "rExpiry\022 .RoomWaterDispenser.lastReplace" +
      "d\032\033.RoomWaterDispenser.expiredB.\n\022RoomWa" +
      "terDispenserB\026RoomWaterDispenserImplP\001b\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_RoomWaterDispenser_lastReplaced_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RoomWaterDispenser_lastReplaced_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RoomWaterDispenser_lastReplaced_descriptor,
        new java.lang.String[] { "Room", "LastReplacedDate", });
    internal_static_RoomWaterDispenser_expired_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_RoomWaterDispenser_expired_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RoomWaterDispenser_expired_descriptor,
        new java.lang.String[] { "Expiry", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
