// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AirVentilation.proto

package AirVentilator;

public final class AirVentilatorImpl {
  private AirVentilatorImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AirVentilator_everyHour_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AirVentilator_everyHour_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AirVentilator_ventilator_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AirVentilator_ventilator_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024AirVentilation.proto\022\rAirVentilator\"\032\n" +
      "\teveryHour\022\r\n\005hours\030\001 \001(\005\"%\n\nventilator\022" +
      "\027\n\017startVentilator\030\001 \001(\t2X\n\016AirVentilati" +
      "on\022F\n\rairVentilator\022\030.AirVentilator.ever" +
      "yHour\032\031.AirVentilator.ventilator0\001B$\n\rAi" +
      "rVentilatorB\021AirVentilatorImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_AirVentilator_everyHour_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_AirVentilator_everyHour_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AirVentilator_everyHour_descriptor,
        new java.lang.String[] { "Hours", });
    internal_static_AirVentilator_ventilator_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_AirVentilator_ventilator_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AirVentilator_ventilator_descriptor,
        new java.lang.String[] { "StartVentilator", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
