// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AirVentilation.proto

package AirVentilator;

public interface everyHourOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AirVentilator.everyHour)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 hours = 1;</code>
   */
  int getHours();
}
