// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AirVentilation.proto

package AirVentilator;

public interface ventilatorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AirVentilator.ventilator)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string startVentilator = 1;</code>
   */
  java.lang.String getStartVentilator();
  /**
   * <code>string startVentilator = 1;</code>
   */
  com.google.protobuf.ByteString
      getStartVentilatorBytes();
}
