// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RoomAir.proto

package RoomAirController;

public interface hourlyAirTrackerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RoomAirController.hourlyAirTracker)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string temperature = 1;</code>
   */
  java.lang.String getTemperature();
  /**
   * <code>string temperature = 1;</code>
   */
  com.google.protobuf.ByteString
      getTemperatureBytes();

  /**
   * <code>string aqi = 2;</code>
   */
  java.lang.String getAqi();
  /**
   * <code>string aqi = 2;</code>
   */
  com.google.protobuf.ByteString
      getAqiBytes();

  /**
   * <code>string airPurifier = 3;</code>
   */
  java.lang.String getAirPurifier();
  /**
   * <code>string airPurifier = 3;</code>
   */
  com.google.protobuf.ByteString
      getAirPurifierBytes();

  /**
   * <code>string carbonMonoxide = 4;</code>
   */
  java.lang.String getCarbonMonoxide();
  /**
   * <code>string carbonMonoxide = 4;</code>
   */
  com.google.protobuf.ByteString
      getCarbonMonoxideBytes();
}
