// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RoomAir.proto

package RoomAirController;

public final class RoomAirImpl {
  private RoomAirImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RoomAirController_roomNum_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RoomAirController_roomNum_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RoomAirController_hourlyAirTracker_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RoomAirController_hourlyAirTracker_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rRoomAir.proto\022\021RoomAirController\"\027\n\007ro" +
      "omNum\022\014\n\004room\030\001 \001(\005\"a\n\020hourlyAirTracker\022" +
      "\013\n\003aqi\030\001 \001(\005\022\023\n\013temperature\030\002 \001(\t\022\023\n\013air" +
      "Purifier\030\003 \001(\t\022\026\n\016carbonMonoxide\030\004 \001(\t2_" +
      "\n\007RoomAir\022T\n\017controllRoomAir\022\032.RoomAirCo" +
      "ntroller.roomNum\032#.RoomAirController.hou" +
      "rlyAirTracker0\001B\"\n\021RoomAirControllerB\013Ro" +
      "omAirImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_RoomAirController_roomNum_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RoomAirController_roomNum_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RoomAirController_roomNum_descriptor,
        new java.lang.String[] { "Room", });
    internal_static_RoomAirController_hourlyAirTracker_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_RoomAirController_hourlyAirTracker_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RoomAirController_hourlyAirTracker_descriptor,
        new java.lang.String[] { "Aqi", "Temperature", "AirPurifier", "CarbonMonoxide", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
