// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RoomAir.proto

package RoomAirController;

public interface roomNumOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RoomAirController.roomNum)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 room = 1;</code>
   */
  int getRoom();
}
