// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RoomAir.proto

package RoomAirController;

public interface roomNumOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RoomAirController.roomNum)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 room = 1;</code>
   */
  int getRoom();

  /**
   * <code>int32 temperature = 2;</code>
   */
  int getTemperature();

  /**
   * <code>int32 aqi = 3;</code>
   */
  int getAqi();

  /**
   * <code>int32 carbonMonoxide = 4;</code>
   */
  int getCarbonMonoxide();
}
