// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PoolWater.proto

package PoolWaterController;

public interface evacuateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PoolWaterController.evacuate)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string evacuateMsg = 1;</code>
   */
  java.lang.String getEvacuateMsg();
  /**
   * <code>string evacuateMsg = 1;</code>
   */
  com.google.protobuf.ByteString
      getEvacuateMsgBytes();
}
