// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PoolWater.proto

package PoolWaterController;

public interface phLevelOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PoolWaterController.phLevel)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 currentPhLevel = 1;</code>
   */
  int getCurrentPhLevel();
}
