// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PoolWater.proto

package PoolWaterController;

public final class PoolWaterImpl {
  private PoolWaterImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PoolWaterController_phLevel_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PoolWaterController_phLevel_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PoolWaterController_evacuate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PoolWaterController_evacuate_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017PoolWater.proto\022\023PoolWaterController\"!" +
      "\n\007phLevel\022\026\n\016currentPhLevel\030\001 \001(\005\"\037\n\010eva" +
      "cuate\022\023\n\013evacuateMsg\030\001 \001(\t2[\n\tPoolWater\022" +
      "N\n\rstopPoolEntry\022\034.PoolWaterController.p" +
      "hLevel\032\035.PoolWaterController.evacuate(\001B" +
      "&\n\023PoolWaterControllerB\rPoolWaterImplP\001b" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_PoolWaterController_phLevel_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PoolWaterController_phLevel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PoolWaterController_phLevel_descriptor,
        new java.lang.String[] { "CurrentPhLevel", });
    internal_static_PoolWaterController_evacuate_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PoolWaterController_evacuate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PoolWaterController_evacuate_descriptor,
        new java.lang.String[] { "EvacuateMsg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
